# Generated by Django 4.2.7 on 2023-11-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="dockerfilebuild", name="filename",),
        migrations.AddField(
            model_name="dockerfilebuild",
            name="file",
            field=models.FileField(default=None, upload_to="dockerfiles/"),
        ),
        migrations.AlterField(
            model_name="dockerfilebuild",
            name="status",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
