# Generated by Django 4.2.7 on 2023-11-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rest_api",
            "0002_remove_dockerfilebuild_filename_dockerfilebuild_file_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="dockerfilebuild",
            old_name="username",
            new_name="docker_username",
        ),
        migrations.AlterField(
            model_name="dockerfilebuild",
            name="status",
            field=models.CharField(default="Stored locally", max_length=50, null=True),
        ),
    ]
