# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Print "Hello, Docker!" when the container launches
CMD ["echo", "WOW, Docker!"]
